name: GoldmanHats
version: '${project.version}'
main: lee.code.hats.GoldmanHats
api-version: 1.19
depend: [GoldmanCore]
commands:
  givehat:
    description: Give yourself a hat.
    permission: hats.command.givehat
    usage: "/givehat &f<hat>"
